routes/admin.php
<?php

use App\Http\Controllers\Admin\CustomPageController;
use App\Http\Controllers\Admin\GuardianBlogController;
use App\Http\Controllers\Admin\InfoController;
use App\Http\Controllers\Admin\keyController;
use App\Http\Controllers\Admin\NewsApiAiController;
use App\Http\Controllers\Admin\NewsApiBlogController;
use App\Http\Controllers\Admin\NewYorkBlogController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\TranslationController;
use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\DashboardController;
use \App\Http\Controllers\LanguageController;
use \App\Http\Controllers\Admin\Authentication\AuthController;
use \App\Http\Controllers\Admin\User\UserController;
use \App\Http\Controllers\Admin\User\RoleController;
use \App\Http\Controllers\Admin\Area\AreaController;
use \App\Http\Controllers\Admin\User\SectionController;

Route::controller(AuthController::class)->group(function () {
    Route::post('login', 'login')->name('admin.login');
    Route::get('login', 'getAdminLogin')->name('admin.get.login');
    Route::get('/', 'index')->name('admin.get.index');
});

Route::group(['middleware' => ['auth']], function () {

    Route::controller(DashboardController::class)->group(function () {
        Route::get('/dashboard', 'dashboardEcommerce')->name('admin.dashboard-ecommerce');
        Route::get('/logout', 'logout')->name('admin.logout');
    });

    Route::group(['prefix' => 'area'], function () {
        Route::controller(AreaController::class)->group(function () {
            Route::post('get-city', 'index')->name('area.cities');
        });
    });

    Route::group(['prefix' => 'users'], function () {

        Route::group(['prefix' => 'employee', 'as' => 'employee.'], function () {
            Route::controller(UserController::class)->group(function () {
                Route::get('index', 'index')->name('index');
                Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
                Route::get('create', 'create')->name('create');
                Route::get('show/{id}', 'show')->name('show');
                Route::get('edit/{id}', 'edit')->name('edit');
                Route::post('update/{id}', 'update')->name('update');
                Route::post('store', 'store')->name('store');
                Route::delete('delete/{id}', 'destroy')->name('destroy');
                Route::get('export', 'export')->name('export');

            });
        });

        Route::group(['prefix' => 'role', 'as' => 'role.'], function () {
            Route::controller(RoleController::class)->group(function () {
                Route::get('index', 'index')->name('index');
                Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
                Route::get('create', 'create')->name('create');
                Route::get('show/{id}', 'show')->name('show');
                Route::get('edit/{id}', 'edit')->name('edit');
                Route::post('update/{id}', 'update')->name('update');
                Route::post('store', 'store')->name('store');
                Route::delete('delete/{id}', 'destroy')->name('destroy');
                Route::get('export', 'export')->name('export');
            });
        });


        Route::group(['prefix' => 'section', 'as' => 'section.'], function () {
            Route::controller(SectionController::class)->group(function () {
                Route::get('index', 'index')->name('index');
                Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
                Route::get('create', 'create')->name('create');
                Route::get('show/{id}', 'show')->name('show');
                Route::get('edit/{id}', 'edit')->name('edit');
                Route::post('update/{id}', 'update')->name('update');
                Route::post('store', 'store')->name('store');
                Route::delete('delete/{id}', 'destroy')->name('destroy');
                Route::get('export', 'export')->name('export');
            });
        });


    });


    //TODO : NewsApi endpoints
    Route::group(['prefix' => 'news-api-blog', 'as' => 'social.blog.'], function () {
        Route::controller(NewsApiBlogController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('update-data', 'updateBlogData')->name('updateBlogData');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
            Route::get('reorder', 'reorder')->name('reorder');
            Route::patch('reorder-post', 'reorderPost')->name('reorder-post');
        });
    });

    //TODO : Guardian endpoints
    Route::group(['prefix' => 'guardian-api-blog', 'as' => 'social.blog.guardian.'], function () {
        Route::controller(GuardianBlogController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('update-data', 'updateBlogData')->name('updateBlogData');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
            Route::get('reorder', 'reorder')->name('reorder');
            Route::patch('reorder-post', 'reorderPost')->name('reorder-post');
        });
    });

    //TODO : New york endpoints
    Route::group(['prefix' => 'new-york-api-blog', 'as' => 'social.blog.york.'], function () {
        Route::controller(NewYorkBlogController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('update-data', 'updateBlogData')->name('updateBlogData');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
            Route::get('reorder', 'reorder')->name('reorder');
            Route::patch('reorder-post', 'reorderPost')->name('reorder-post');
        });
    });

    //TODO : NewsApiAi endpoints
    Route::group(['prefix' => 'news-api-ai-blog', 'as' => 'social.blog.ai.'], function () {
        Route::controller(NewsApiAiController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('update-data', 'updateBlogData')->name('updateBlogData');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
            Route::get('reorder', 'reorder')->name('reorder');
            Route::patch('reorder-post', 'reorderPost')->name('reorder-post');
        });
    });

    Route::group(['prefix' => 'key', 'as' => 'key.'], function () {
        Route::controller(keyController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('create', 'create')->name('create');
            Route::get('edit/{id}', 'edit')->name('edit');
            Route::post('update/{id}', 'update')->name('update');
            Route::post('store', 'store')->name('store');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
        });
    });

    Route::group(['prefix' => 'info', 'as' => 'info.'], function () {
        Route::controller(InfoController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('create', 'create')->name('create');
            Route::get('edit/{id}', 'edit')->name('edit');
            Route::post('update/{id}', 'update')->name('update');
            Route::post('store', 'store')->name('store');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
        });
    });


    Route::group(['prefix' => 'custom', 'as' => 'custom.'], function () {
        Route::controller(CustomPageController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('create', 'create')->name('create');
            Route::get('edit/{id}', 'edit')->name('edit');
            Route::post('update/{id}', 'update')->name('update');
            Route::post('store', 'store')->name('store');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
        });
    });

    Route::group(['prefix' => 'setting', 'as' => 'setting.'], function () {
        Route::controller(SettingController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::post('update', 'update')->name('update');
        });
    });

    Route::group(['prefix' => 'translation', 'as' => 'translation.'], function () {
        Route::controller(TranslationController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('edit/{id}', 'edit')->name('edit');
            Route::post('update/{key}', 'update')->name('update');

routes/web.php
<?php

use App\Http\Controllers\Website\MainController;
use Illuminate\Support\Facades\Route;
///*
//|--------------------------------------------------------------------------
//| Web Routes
//|--------------------------------------------------------------------------
//|
//| Here is where you can register web routes for your application. These
//| routes are loaded by the RouteServiceProvider within a group which
//| contains the "web" middleware group. Now create something great!
//|
//*/
//


Route::get('/', [MainController::class, 'index'])->name('web.index');

app/Models/Role.php
<?php

namespace App\Models;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{
    public $guarded = [];
}

app/Http/Controllers/Admin/User/RoleController.php
<?php

namespace App\Http\Controllers\Admin\User;

use App\Exports\RoleExport;
use App\Http\Controllers\Admin\MainDashboardController;
use App\Http\Requests\Admin\User\Role\RoleStoreRequest;
use App\Http\Requests\Admin\User\Role\RoleUpdateRequest;
use App\Http\Resources\Dashboard\Role\RoleResource;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class RoleController extends MainDashboardController
{
    public function __construct(Request $request)
    {
        $this->dashboardPaginate = $request->has('page_counter') ? ($request->page_counter == 0 ? $this->dashboardPaginate : $request->page_counter) : $request->dashboardPaginate;

        //create read update delete
        $this->middleware(['permission:read_role'])->only('index');
        $this->middleware(['permission:read_role'])->only('export');
        $this->middleware(['permission:create_role'])->only('create');
        $this->middleware(['permission:update_role'])->only('edit');
        $this->middleware(['permission:delete_role'])->only('destroy');

    }//end of constructor


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $breadcrumbs = [
            ['link' => route('admin.dashboard-ecommerce'), 'name' => _t('dashboard.Dashboard')],
            ['name' => _t('dashboard.Roles')]
        ];

        $data = app('servicesV1')->roleService->getAllRoles($request)->paginate($this->dashboardPaginate);

        $data->getCollection()->transform(function ($item) use ($request) {
            return (new RoleResource($item))->toArray();
        });

        return view('admin.user.role.index', compact('data', 'breadcrumbs'));
    }


    public function fetchData(Request $request)
    {
        $data = app('servicesV1')->roleService->filterRoles($request)->paginate($this->dashboardPaginate);

        $data->getCollection()->transform(function ($item) use ($request) {
            return (new RoleResource($item))->toArray($request);
        });

        return view('admin.user.role.include.pagination_data', compact('data'))->render();
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $breadcrumbs = [
            ['link' => route('admin.dashboard-ecommerce'), 'name' => _t('dashboard.Dashboard')],
            ['link' => route('role.index'), 'name' => _t('dashboard.Roles')],
            ['name' => _t('dashboard.Create')]
        ];

        return view('admin.user.role.create', compact('breadcrumbs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(RoleStoreRequest $request)
    {
        $role = app('servicesV1')->roleService->storeRole($request);

               if (!$role) {
            return redirect()->route('role.index')->with('failed', _t('message.There is an error'));
        }

        return redirect()->route('role.index')->with('success', _t('message.The data created successful'));
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = app('servicesV1')->roleService->findRole($id);

        $breadcrumbs = [
            ['link' => route('admin.dashboard-ecommerce'), 'name' => _t('dashboard.Dashboard')],
            ['link' => route('role.index'), 'name' => _t('dashboard.Roles')],
            ['name' => _t('dashboard.Show')],
            ['name' => "#" . $role->id . ' - ' . $role->created_at->format('m/d/Y')]
        ];

        $data = (new RoleResource($role))->toArray();

        return view('admin.user.role.show', compact('data', 'breadcrumbs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $role = app('servicesV1')->roleService->findRole($id);

        $breadcrumbs = [
            ['link' => route('admin.dashboard-ecommerce'), 'name' => _t('dashboard.Dashboard')],
            ['link' => route('role.index'), 'name' => _t('dashboard.Roles')],
            ['name' => _t('dashboard.Edit')],
            ['name' => "#" . $role->id . ' - ' . $role->created_at->format('m/d/Y')]
        ];

        $data = (new RoleResource($role))->toArray();

        return view('admin.user.role.edit', compact('data', 'breadcrumbs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(RoleUpdateRequest $request, $id)
    {

        $role = app('servicesV1')->roleService->updateRole($request,$id);

        if (!$role) {
            return redirect()->route('role.index')->with('failed', _t('message.There is an error'));
        }

        return redirect()->route('role.index')->with('success', _t('message.The data updated successful'));

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $role = app('servicesV1')->roleService->deleteRole($id);

        if (!$role){
            return redirect()->route('role.index')->with('failed', _t('message.There is an error'));
        }

        return redirect()->route('role.index')->with('success', _t('message.The data deleted successful'));

    }

    public function export()
    {
        return Excel::download(new RoleExport(), _t('dashboard.Roles').'.xlsx');
    }
}

resources/views/admin/user/role/include/filters.blade.php
<script>
    $(document).ready(function () {

        let timer;

        function fetch_data(page, sort_type, column_name, query, page_counter) {
            $.ajax({
                url: "{{ route('role.fetchData') }}",
                data: {
                    page: page,
                    sorttype: sort_type,
                    query: query,
                    page_counter: page_counter,
                },
                success: function (data) {
                    $('tbody').html('');
                    $('tbody').html(data);
                }
            })
        }


        $(document).on('keyup', '#search', function () {

            clearTimeout(timer);
            var query = $('#search').val();
            var column_name = $('#hidden_column_name').val();
            var sort_type = $('#hidden_sort_type').val();
            var page_counter = $('#page_counter').val();
            var page = $('#hidden_page').val();
            timer = setTimeout(function () {
                fetch_data(page, sort_type, column_name, query, page_counter);
            }, time_filter);
        });


        $("#page_counter,#hidden_sort_type").change(function () {

            var query = $('#search').val();
            var column_name = $('#hidden_column_name').val();
            var sort_type = $('#hidden_sort_type').val();
            var page_counter = $('#page_counter').val();
            var page = $('#hidden_page').val();
            fetch_data(page, sort_type, column_name, query, page_counter);
        });


        $(document).on('click', '.pagination a', function (event) {
            event.preventDefault();
            var page = $(this).attr('href').split('page=')[1];
            $('#hidden_page').val(page);
            var column_name = $('#hidden_column_name').val();
            var sort_type = $('#hidden_sort_type').val();
            var query = $('#search').val();
            var page_counter = $('#page_counter').val();

            $('li').removeClass('active');
            $(this).parent().addClass('active');
            fetch_data(page, sort_type, column_name, query, page_counter);
        });
    });
</script>

resources/views/admin/user/role/include/pagination_data.blade.php
@if(count($data) > 0)
    @foreach ($data as $index => $role)
        <tr>
            <td>{{$role['id']}}</td>
            <td>{{$role['name']}}</td>
            <td>{{$role['employees_number']}}</td>
            <td>
               <span
                   class="badge rounded-pill badge-light-{{$role['is_main_class']}}">{{$role['is_main_string']}}</span>
            </td>
            <td>
                <div class="dropdown">
                    <button type="button" class="btn btn-sm dropdown-toggle hide-arrow py-0"
                            data-bs-toggle="dropdown">
                        <i data-feather="more-vertical"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-end">
                        @permission('update_role')
                        <a class="dropdown-item" href="{{route('role.edit',$role['id'])}}">
                            <i data-feather="edit-2" class="me-50"></i>
                            <span>{{_t('dashboard.Edit')}}</span>
                        </a>
                        @endpermission


                        @permission('read_role')
                        <a class="dropdown-item" href="{{route('role.show',$role['id'])}}">
                            <i data-feather="eye" class="me-50"></i>
                            <span>{{_t('dashboard.Show')}}</span>
                        </a>
                        @endpermission


                        @if(!$role['is_main'])
                            @permission('delete_role')
                            <div class="col-4">
                                <form method="post" id="myForm"
                                      action="{{route('role.destroy',$role['id'])}}">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn delete dropdown-item"><i data-feather="trash"
                                                                                class="me-50"></i>
                                        <span>{{_t('dashboard.Delete')}}</span></button>
                                </form>
                            </div>
                            @endpermission
                        @endif

                    </div>
                </div>
            </td>

        </tr>
    @endforeach
    <td colspan="3">
        {!! $data->appends(request()->query())->links("pagination::bootstrap-4") !!}
    </td>

@else
    @include('admin.include.no_data')
@endif


<!-- this script is important for every paginate component to show the feather spans when filter -->
<script>
    $(document).ready(function () {
        feather.replace()
    })
</script>

resources/views/admin/user/role/include/scripts.blade.php
<script>
    $(document).ready(function () {

        $("#regForm").validate({
            rules: {
                name_ar: "required",
                name: "required",
                description_ar: "required",
                description: "required",
            },
            messages: {
                name_ar: {
                    required: "{{_t('validation.The field is required')}}",
                },
                name: {
                    required: "{{_t('validation.The field is required')}}",
                },
                description_ar: {
                    required: "{{_t('validation.The field is required')}}",
                },
                description: {
                    required: "{{_t('validation.The field is required')}}",
                },
            }
        });
    });
</script>

resources/views/admin/user/role/include/styles.blade.php
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<style>

    .pagination {
        justify-content: center !important;
        margin-top: 10px !important;
    }

    td {
        white-space: nowrap;
        max-width: 100%;
    }

</style>


<style>
    select2-container--default {
        display: flex !important;
    }
</style>
<style>
    .form-switch .form-check-label .switch-text-left i, .form-switch .form-check-label .switch-text-left svg, .form-switch .form-check-label .switch-text-right i, .form-switch .form-check-label .switch-text-right svg, .form-switch .form-check-label .switch-icon-left i, .form-switch .form-check-label .switch-icon-left svg, .form-switch .form-check-label .switch-icon-right i, .form-switch .form-check-label .switch-icon-right svg {
        height: 13px;
        width: 13px;
        margin-top: 6px;
        font-size: 13px;
    }
</style>