routes/admin.php
<?php

use App\Http\Controllers\Admin\CustomPageController;
use App\Http\Controllers\Admin\GuardianBlogController;
use App\Http\Controllers\Admin\InfoController;
use App\Http\Controllers\Admin\keyController;
use App\Http\Controllers\Admin\NewsApiAiController;
use App\Http\Controllers\Admin\NewsApiBlogController;
use App\Http\Controllers\Admin\NewYorkBlogController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\TranslationController;
use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\DashboardController;
use \App\Http\Controllers\LanguageController;
use \App\Http\Controllers\Admin\Authentication\AuthController;
use \App\Http\Controllers\Admin\User\UserController;
use \App\Http\Controllers\Admin\User\RoleController;
use \App\Http\Controllers\Admin\Area\AreaController;
use \App\Http\Controllers\Admin\User\SectionController;

Route::controller(AuthController::class)->group(function () {
    Route::post('login', 'login')->name('admin.login');
    Route::get('login', 'getAdminLogin')->name('admin.get.login');
    Route::get('/', 'index')->name('admin.get.index');
});

Route::group(['middleware' => ['auth']], function () {

    Route::controller(DashboardController::class)->group(function () {
        Route::get('/dashboard', 'dashboardEcommerce')->name('admin.dashboard-ecommerce');
        Route::get('/logout', 'logout')->name('admin.logout');
    });

    Route::group(['prefix' => 'area'], function () {
        Route::controller(AreaController::class)->group(function () {
            Route::post('get-city', 'index')->name('area.cities');
        });
    });

    Route::group(['prefix' => 'users'], function () {

        Route::group(['prefix' => 'employee', 'as' => 'employee.'], function () {
            Route::controller(UserController::class)->group(function () {
                Route::get('index', 'index')->name('index');
                Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
                Route::get('create', 'create')->name('create');
                Route::get('show/{id}', 'show')->name('show');
                Route::get('edit/{id}', 'edit')->name('edit');
                Route::post('update/{id}', 'update')->name('update');
                Route::post('store', 'store')->name('store');
                Route::delete('delete/{id}', 'destroy')->name('destroy');
                Route::get('export', 'export')->name('export');

            });
        });

        Route::group(['prefix' => 'role', 'as' => 'role.'], function () {
            Route::controller(RoleController::class)->group(function () {
                Route::get('index', 'index')->name('index');
                Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
                Route::get('create', 'create')->name('create');
                Route::get('show/{id}', 'show')->name('show');
                Route::get('edit/{id}', 'edit')->name('edit');
                Route::post('update/{id}', 'update')->name('update');
                Route::post('store', 'store')->name('store');
                Route::delete('delete/{id}', 'destroy')->name('destroy');
                Route::get('export', 'export')->name('export');
            });
        });


        Route::group(['prefix' => 'section', 'as' => 'section.'], function () {
            Route::controller(SectionController::class)->group(function () {
                Route::get('index', 'index')->name('index');
                Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
                Route::get('create', 'create')->name('create');
                Route::get('show/{id}', 'show')->name('show');
                Route::get('edit/{id}', 'edit')->name('edit');
                Route::post('update/{id}', 'update')->name('update');
                Route::post('store', 'store')->name('store');
                Route::delete('delete/{id}', 'destroy')->name('destroy');
                Route::get('export', 'export')->name('export');
            });
        });


    });


    //TODO : NewsApi endpoints
    Route::group(['prefix' => 'news-api-blog', 'as' => 'social.blog.'], function () {
        Route::controller(NewsApiBlogController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('update-data', 'updateBlogData')->name('updateBlogData');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
            Route::get('reorder', 'reorder')->name('reorder');
            Route::patch('reorder-post', 'reorderPost')->name('reorder-post');
        });
    });

    //TODO : Guardian endpoints
    Route::group(['prefix' => 'guardian-api-blog', 'as' => 'social.blog.guardian.'], function () {
        Route::controller(GuardianBlogController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('update-data', 'updateBlogData')->name('updateBlogData');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
            Route::get('reorder', 'reorder')->name('reorder');
            Route::patch('reorder-post', 'reorderPost')->name('reorder-post');
        });
    });

    //TODO : New york endpoints
    Route::group(['prefix' => 'new-york-api-blog', 'as' => 'social.blog.york.'], function () {
        Route::controller(NewYorkBlogController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('update-data', 'updateBlogData')->name('updateBlogData');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
            Route::get('reorder', 'reorder')->name('reorder');
            Route::patch('reorder-post', 'reorderPost')->name('reorder-post');
        });
    });

    //TODO : NewsApiAi endpoints
    Route::group(['prefix' => 'news-api-ai-blog', 'as' => 'social.blog.ai.'], function () {
        Route::controller(NewsApiAiController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('update-data', 'updateBlogData')->name('updateBlogData');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
            Route::get('reorder', 'reorder')->name('reorder');
            Route::patch('reorder-post', 'reorderPost')->name('reorder-post');
        });
    });

    Route::group(['prefix' => 'key', 'as' => 'key.'], function () {
        Route::controller(keyController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('create', 'create')->name('create');
            Route::get('edit/{id}', 'edit')->name('edit');
            Route::post('update/{id}', 'update')->name('update');
            Route::post('store', 'store')->name('store');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
        });
    });

    Route::group(['prefix' => 'info', 'as' => 'info.'], function () {
        Route::controller(InfoController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('create', 'create')->name('create');
            Route::get('edit/{id}', 'edit')->name('edit');
            Route::post('update/{id}', 'update')->name('update');
            Route::post('store', 'store')->name('store');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
        });
    });


    Route::group(['prefix' => 'custom', 'as' => 'custom.'], function () {
        Route::controller(CustomPageController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('create', 'create')->name('create');
            Route::get('edit/{id}', 'edit')->name('edit');
            Route::post('update/{id}', 'update')->name('update');
            Route::post('store', 'store')->name('store');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
        });
    });

    Route::group(['prefix' => 'setting', 'as' => 'setting.'], function () {
        Route::controller(SettingController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::post('update', 'update')->name('update');
        });
    });

    Route::group(['prefix' => 'translation', 'as' => 'translation.'], function () {
        Route::controller(TranslationController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('edit/{id}', 'edit')->name('edit');
            Route::post('update/{key}', 'update')->name('update');

routes/web.php
<?php

use App\Http\Controllers\Website\MainController;
use Illuminate\Support\Facades\Route;
///*
//|--------------------------------------------------------------------------
//| Web Routes
//|--------------------------------------------------------------------------
//|
//| Here is where you can register web routes for your application. These
//| routes are loaded by the RouteServiceProvider within a group which
//| contains the "web" middleware group. Now create something great!
//|
//*/
//


Route::get('/', [MainController::class, 'index'])->name('web.index');

app/Models/Info/Info.php
<?php

namespace App\Models\Info;

use Astrotomic\Translatable\Contracts\Translatable as TranslatableContract;
use Astrotomic\Translatable\Translatable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Info extends Model implements TranslatableContract
{
    use HasFactory;
    use Translatable;

    protected $table = 'infos';
    protected $fillable = ['is_active','type'];

    public $translatedAttributes = ['title','description'];


    public function setTranslatedAttributes(Request $request)
    {
        foreach (config('translatable.locales') as $locale) {
            if ($request->has($locale)) {
                $this->getTranslationOrNew($locale)->title = isset($request->get($locale)['title']) ? $request->get($locale)['title'] : null;
                $this->getTranslationOrNew($locale)->description = isset($request->get($locale)['description']) ? $request->get($locale)['description'] : null;
            }

        }
    }

}

app/Models/Info/InfoTranslation.php
<?php

namespace App\Models\Info;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class InfoTranslation extends Model
{
    use HasFactory;
    protected $table = 'info_translations_table';
}

app/Http/Controllers/Admin/InfoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Enums\InfoType;
use App\Exports\InfoExport;
use App\Exports\SocialExport;
use App\Http\Resources\Dashboard\Info\InfoResource;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;

class InfoController extends MainDashboardController
{
    public function __construct(Request $request)
    {
        $this->dashboardPaginate = $request->has('page_counter') ? ($request->page_counter == 0 ? $this->dashboardPaginate : $request->page_counter) : $this->dashboardPaginate;

        //create read update delete
        $this->middleware(['permission:read_info'])->only('index');
        $this->middleware(['permission:create_info'])->only('create');
        $this->middleware(['permission:update_info'])->only('edit');
        $this->middleware(['permission:delete_info'])->only('destroy');

    }//end of constructor


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $breadcrumbs = [
            ['link' => route('admin.dashboard-ecommerce'), 'name' => _t('dashboard.Dashboard')],
            ['name' => _t('dashboard.Infos')]
        ];

        $data = app('servicesV1')->infoService->getAllData()->paginate($this->dashboardPaginate);

        $data->getCollection()->transform(function ($item) {
            return (new InfoResource($item))->toArray();
        });

        return view('admin.info.index', compact('data', 'breadcrumbs'));
    }

    public function fetchData(Request $request)
    {

        $data = app('servicesV1')->infoService->filterData($request)->paginate($this->dashboardPaginate);

        $data->getCollection()->transform(function ($item) {
            return (new InfoResource($item))->toArray();
        });

        return view('admin.info.include.pagination_data', compact('data'))->render();
    }

    public function create()
    {
        $breadcrumbs = [
            ['link' => route('admin.dashboard-ecommerce'), 'name' => _t('dashboard.Dashboard')],
            ['link' => route('info.index'), 'name' => _t('dashboard.Infos')],
            ['name' => _t('dashboard.Create')]
        ];

        $types = InfoType::getValues();
        $infos = app('servicesV1')->infoService->getAllTypeStore();

        return view('admin.info.create', compact('breadcrumbs','types','infos'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $result = app('servicesV1')->infoService->storeData($request);

        if ($result) {
            return redirect()->route('info.index')->with('success', _t('message.The data created successful'));
        }

        return redirect()->route('info.index')->with('failed', _t('message.There is an error'));
    }

    public function show($id)
    {
        $data = app('servicesV1')->infoService->findData($id);

        $breadcrumbs = [
            ['link' => route('admin.dashboard-ecommerce'), 'name' => _t('dashboard.Dashboard')],
            ['link' => route('info.index'), 'name' => _t('dashboard.Infos')],
            ['name' => _t('dashboard.Show')],
            ['name' => "#" . $data->id . ' - ' . $data->created_at->format('m/d/Y')]

        ];

        $data = (new InfoResource($data))->toArray();

        return view('admin.info.show', compact('data', 'breadcrumbs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = app('servicesV1')->infoService->findData($id);

        $breadcrumbs = [
            ['link' => route('admin.dashboard-ecommerce'), 'name' => _t('dashboard.Dashboard')],
            ['link' => route('info.index'), 'name' => _t('dashboard.Infos')],
            ['name' => _t('dashboard.Edit')],
            ['name' => "#" . $data->id . ' - ' . $data->created_at->format('m/d/Y')]

        ];

        $data = (new InfoResource($data))->toArray();
        $types = InfoType::getValues();
        $infos = app('servicesV1')->infoService->getAllTypeStore();

        return view('admin.info.edit', compact('data','types','infos','breadcrumbs'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $result = app('servicesV1')->infoService->updateData($request,$id);

        if ($result) {
            return redirect()->route('info.index')->with('success', _t('message.The data updated successful'));
        }
        return redirect()->route('info.index')->with('failed', _t('message.There is an error'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $result = app('servicesV1')->infoService->deleteData($id);

        if ($result) {
            return redirect()->route('info.index')->with('success', _t('message.The data deleted successful'));
        }
        return redirect()->route('info.index')->with('failed', _t('message.There is an error'));
    }


    public function export()
    {

        return Excel::download(new InfoExport(), _t('dashboard.Infos') . '.xlsx');
    }

}

resources/views/admin/info/include/filters.blade.php
<script>
    $(document).ready(function () {

        let timer;

        function fetch_data(page, sort_type, column_name, query, page_counter) {
            $.ajax({
                url: "{{ route('info.fetchData') }}",
                data: {
                    page: page,
                    sortby: sort_type,
                    query: query,
                    page_counter: page_counter,
                },
                success: function (data) {
                    $('tbody').html('');
                    $('tbody').html(data);
                }
            })
        }


        $(document).on('keyup', '#search', function () {

            clearTimeout(timer);
            var query = $('#search').val();
            var column_name = $('#hidden_column_name').val();
            var sort_type = $('#hidden_sort_type').val();
            var page_counter = $('#page_counter').val();
            var page = $('#hidden_page').val();
            timer = setTimeout(function () {
                fetch_data(page, sort_type, column_name, query, page_counter);
            }, 1000);
        });


        $("#STATUS,#page_counter,#hidden_sort_type").change(function () {

            var query = $('#search').val();
            var column_name = $('#hidden_column_name').val();
            var sort_type = $('#hidden_sort_type').val();
            var page_counter = $('#page_counter').val();
            var page = $('#hidden_page').val();
            var type_operation = $('#type_operation').val();
            fetch_data(page, sort_type, column_name, query, page_counter,type_operation);
        });



        $(document).on('click', '.pagination a', function (event) {
            event.preventDefault();
            var page = $(this).attr('href').split('page=')[1];
            $('#hidden_page').val(page);
            var query = $('#search').val();
            var column_name = $('#hidden_column_name').val();
            var sort_type = $('#hidden_sort_type').val();
            var page_counter = $('#page_counter').val();

            $('li').removeClass('active');
            $(this).parent().addClass('active');
            fetch_data(page, sort_type, column_name, query, page_counter);
        });
    });
</script>

resources/views/admin/info/include/pagination_data.blade.php
@if(count($data) > 0)
    @foreach ($data as $index => $info)
        <tr class="{{getTrTableClass($info['is_active'])}}">
            <td>{{$info['id']}}</td>
            <td>{{$info['title']}}</td>

            <td>
                           <span
                            class="badge rounded-pill badge-light-info">{{$info['type_string']}}</span>
            </td>
            <td>
                           <span
                               class="badge rounded-pill badge-light-{{$info['is_active_class']}}">{{$info['is_active_string']}}</span>
            </td>
            <td>
                                                            <span
                                                                class="badge rounded-pill badge-light-warning">{{$info['date']}}</span>
            </td>

            <td>
                <div class="dropdown">
                    <button type="button"
                            class="btn btn-sm dropdown-toggle hide-arrow py-0"
                            data-bs-toggle="dropdown">
                        <i data-feather="more-vertical"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-end">

                        @permission('read_info')
                        <a class="dropdown-item" href="{{route('info.show',$info['id'])}}">
                            <i data-feather="eye" class="me-50"></i>
                            <span>{{_t('dashboard.Show')}}</span>
                        </a>
                        @endpermission

                        @permission('update_info')
                        <a class="dropdown-item"
                           href="{{route('info.edit',$info['id'])}}">
                            <i data-feather="edit-2" class="me-50"></i>
                            <span>{{_t('dashboard.Edit')}}</span>
                        </a>
                        @endpermission

                        @permission('delete_info')
                        <div class="col-4">
                            <form method="post" id="myForm"
                                  action="{{route('info.destroy',$info['id'])}}">
                                @csrf
                                @method('DELETE')


                                <button
                                    style="display: inline-flex;width: 137px;"
                                    class="btn delete dropdown-item"><i
                                        data-feather="trash" class="me-50"></i>
                                    <span>{{_t('dashboard.Delete')}}</span></button>
                            </form>
                        </div>
                        @endpermission
                    </div>
                </div>
            </td>
        </tr>
    @endforeach
    <td colspan="3">
        {!! $data->appends(request()->query())->links("pagination::bootstrap-4") !!}
    </td>
@else
    @include('admin.include.no_data')
@endif
<script>
    $(document).ready(function () {
        feather.replace()
    })
</script>

resources/views/admin/info/include/scripts.blade.php
<script>
    $(document).ready(function () {


        $("#regForm").validate({
            rules: {

            },
            messages: {
                type: {
                    required: "{{_t('validation.The field is required')}}",
                }
            }
        });
    });
</script>