routes/admin.php
<?php

use App\Http\Controllers\Admin\CustomPageController;
use App\Http\Controllers\Admin\GuardianBlogController;
use App\Http\Controllers\Admin\InfoController;
use App\Http\Controllers\Admin\keyController;
use App\Http\Controllers\Admin\NewsApiAiController;
use App\Http\Controllers\Admin\NewsApiBlogController;
use App\Http\Controllers\Admin\NewYorkBlogController;
use App\Http\Controllers\Admin\SettingController;
use App\Http\Controllers\Admin\TranslationController;
use Illuminate\Support\Facades\Route;
use \App\Http\Controllers\DashboardController;
use \App\Http\Controllers\LanguageController;
use \App\Http\Controllers\Admin\Authentication\AuthController;
use \App\Http\Controllers\Admin\User\UserController;
use \App\Http\Controllers\Admin\User\RoleController;
use \App\Http\Controllers\Admin\Area\AreaController;
use \App\Http\Controllers\Admin\User\SectionController;

Route::controller(AuthController::class)->group(function () {
    Route::post('login', 'login')->name('admin.login');
    Route::get('login', 'getAdminLogin')->name('admin.get.login');
    Route::get('/', 'index')->name('admin.get.index');
});

Route::group(['middleware' => ['auth']], function () {

    Route::controller(DashboardController::class)->group(function () {
        Route::get('/dashboard', 'dashboardEcommerce')->name('admin.dashboard-ecommerce');
        Route::get('/logout', 'logout')->name('admin.logout');
    });

    Route::group(['prefix' => 'area'], function () {
        Route::controller(AreaController::class)->group(function () {
            Route::post('get-city', 'index')->name('area.cities');
        });
    });

    Route::group(['prefix' => 'users'], function () {

        Route::group(['prefix' => 'employee', 'as' => 'employee.'], function () {
            Route::controller(UserController::class)->group(function () {
                Route::get('index', 'index')->name('index');
                Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
                Route::get('create', 'create')->name('create');
                Route::get('show/{id}', 'show')->name('show');
                Route::get('edit/{id}', 'edit')->name('edit');
                Route::post('update/{id}', 'update')->name('update');
                Route::post('store', 'store')->name('store');
                Route::delete('delete/{id}', 'destroy')->name('destroy');
                Route::get('export', 'export')->name('export');

            });
        });

        Route::group(['prefix' => 'role', 'as' => 'role.'], function () {
            Route::controller(RoleController::class)->group(function () {
                Route::get('index', 'index')->name('index');
                Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
                Route::get('create', 'create')->name('create');
                Route::get('show/{id}', 'show')->name('show');
                Route::get('edit/{id}', 'edit')->name('edit');
                Route::post('update/{id}', 'update')->name('update');
                Route::post('store', 'store')->name('store');
                Route::delete('delete/{id}', 'destroy')->name('destroy');
                Route::get('export', 'export')->name('export');
            });
        });


        Route::group(['prefix' => 'section', 'as' => 'section.'], function () {
            Route::controller(SectionController::class)->group(function () {
                Route::get('index', 'index')->name('index');
                Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
                Route::get('create', 'create')->name('create');
                Route::get('show/{id}', 'show')->name('show');
                Route::get('edit/{id}', 'edit')->name('edit');
                Route::post('update/{id}', 'update')->name('update');
                Route::post('store', 'store')->name('store');
                Route::delete('delete/{id}', 'destroy')->name('destroy');
                Route::get('export', 'export')->name('export');
            });
        });


    });


    //TODO : NewsApi endpoints
    Route::group(['prefix' => 'news-api-blog', 'as' => 'social.blog.'], function () {
        Route::controller(NewsApiBlogController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('update-data', 'updateBlogData')->name('updateBlogData');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
            Route::get('reorder', 'reorder')->name('reorder');
            Route::patch('reorder-post', 'reorderPost')->name('reorder-post');
        });
    });

    //TODO : Guardian endpoints
    Route::group(['prefix' => 'guardian-api-blog', 'as' => 'social.blog.guardian.'], function () {
        Route::controller(GuardianBlogController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('update-data', 'updateBlogData')->name('updateBlogData');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
            Route::get('reorder', 'reorder')->name('reorder');
            Route::patch('reorder-post', 'reorderPost')->name('reorder-post');
        });
    });

    //TODO : New york endpoints
    Route::group(['prefix' => 'new-york-api-blog', 'as' => 'social.blog.york.'], function () {
        Route::controller(NewYorkBlogController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('update-data', 'updateBlogData')->name('updateBlogData');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
            Route::get('reorder', 'reorder')->name('reorder');
            Route::patch('reorder-post', 'reorderPost')->name('reorder-post');
        });
    });

    //TODO : NewsApiAi endpoints
    Route::group(['prefix' => 'news-api-ai-blog', 'as' => 'social.blog.ai.'], function () {
        Route::controller(NewsApiAiController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('update-data', 'updateBlogData')->name('updateBlogData');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
            Route::get('reorder', 'reorder')->name('reorder');
            Route::patch('reorder-post', 'reorderPost')->name('reorder-post');
        });
    });

    Route::group(['prefix' => 'key', 'as' => 'key.'], function () {
        Route::controller(keyController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('create', 'create')->name('create');
            Route::get('edit/{id}', 'edit')->name('edit');
            Route::post('update/{id}', 'update')->name('update');
            Route::post('store', 'store')->name('store');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
        });
    });

    Route::group(['prefix' => 'info', 'as' => 'info.'], function () {
        Route::controller(InfoController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('create', 'create')->name('create');
            Route::get('edit/{id}', 'edit')->name('edit');
            Route::post('update/{id}', 'update')->name('update');
            Route::post('store', 'store')->name('store');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
            Route::get('export', 'export')->name('export');
        });
    });


    Route::group(['prefix' => 'custom', 'as' => 'custom.'], function () {
        Route::controller(CustomPageController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('show/{id}', 'show')->name('show');
            Route::get('/pagination/fetch-data', 'fetchData')->name('fetchData');
            Route::get('create', 'create')->name('create');
            Route::get('edit/{id}', 'edit')->name('edit');
            Route::post('update/{id}', 'update')->name('update');
            Route::post('store', 'store')->name('store');
            Route::delete('delete/{id}', 'destroy')->name('destroy');
        });
    });

    Route::group(['prefix' => 'setting', 'as' => 'setting.'], function () {
        Route::controller(SettingController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::post('update', 'update')->name('update');
        });
    });

    Route::group(['prefix' => 'translation', 'as' => 'translation.'], function () {
        Route::controller(TranslationController::class)->group(function () {
            Route::get('index', 'index')->name('index');
            Route::get('edit/{id}', 'edit')->name('edit');
            Route::post('update/{key}', 'update')->name('update');

routes/web.php
<?php

use App\Http\Controllers\Website\MainController;
use Illuminate\Support\Facades\Route;
///*
//|--------------------------------------------------------------------------
//| Web Routes
//|--------------------------------------------------------------------------
//|
//| Here is where you can register web routes for your application. These
//| routes are loaded by the RouteServiceProvider within a group which
//| contains the "web" middleware group. Now create something great!
//|
//*/
//


Route::get('/', [MainController::class, 'index'])->name('web.index');

resources/views/admin/york/include/filters.blade.php
<script>
    $(document).ready(function () {

        let timer;

        function fetch_data(page, sort_type, column_name, source, page_counter,category,query,publish_date) {
            $.ajax({
                url: "{{ route('social.blog.york.fetchData') }}",
                data: {
                    page: page,
                    sortby: sort_type,
                    query: query,
                    page_counter: page_counter,
                    source: source,
                    category: category,
                    publish_date: publish_date,
                },
                success: function (data) {
                    $('tbody').html('');
                    $('tbody').html(data);
                }
            })
        }


        $(document).on('keyup', '#search', function () {

            clearTimeout(timer);
            var query = $('#search').val();
            var column_name = $('#hidden_column_name').val();
            var sort_type = $('#hidden_sort_type').val();
            var page_counter = $('#page_counter').val();
            var source = $('#source').val();
            var category = $('#category').val();
            var page = $('#hidden_page').val();
            var publish_date = $('#publish_date').val();

            timer = setTimeout(function () {
                fetch_data(page, sort_type, column_name, source, page_counter,category,query,publish_date);
            }, 1000);
        });


        $("#category,#page_counter,#hidden_sort_type,#source,#publish_date").change(function () {

            var query = $('#search').val();
            var column_name = $('#hidden_column_name').val();
            var sort_type = $('#hidden_sort_type').val();
            var page_counter = $('#page_counter').val();
            var source = $('#source').val();
            var category = $('#category').val();
            var page = $('#hidden_page').val();
            var publish_date = $('#publish_date').val();

            fetch_data(page, sort_type, column_name, source, page_counter,category,query,publish_date);
        });



        $(document).on('click', '.pagination a', function (event) {
            event.preventDefault();
            var page = $(this).attr('href').split('page=')[1];
            $('#hidden_page').val(page);
            var query = $('#search').val();
            var column_name = $('#hidden_column_name').val();
            var sort_type = $('#hidden_sort_type').val();
            var page_counter = $('#page_counter').val();
            var source = $('#source').val();
            var category = $('#category').val();
            var publish_date = $('#publish_date').val();

            $('li').removeClass('active');
            $(this).parent().addClass('active');
            fetch_data(page, sort_type, column_name, source, page_counter,category,query,publish_date);
        });
    });
</script>

resources/views/admin/york/include/pagination_data.blade.php
@if(count($blogs) > 0)
    @foreach ($blogs as $index => $blog)
        <tr>
            <td>{{$blog['id']}}</td>
            <td>{{$blog['title']}}</td>

            <td>
               <span
                   class="badge rounded-pill badge-light-success">{{$blog['author']}}</span>
            </td>

            <td>
               <span
                    class="badge rounded-pill badge-light-info">{{$blog['category_name']}}</span>
            </td>

            <td>
               <span
                    class="badge rounded-pill badge-light-primary">{{$blog['source_name']}}</span>
            </td>
            <td>{{$blog['published_at_format']}}</td>
            <td>
                <div class="dropdown">
                    <button type="button"
                            class="btn btn-sm dropdown-toggle hide-arrow py-0"
                            data-bs-toggle="dropdown">
                        <i data-feather="more-vertical"></i>
                    </button>
                    <div class="dropdown-menu dropdown-menu-end">

                        @permission('read_blog')
                        <a class="dropdown-item" href="{{route('social.blog.york.show',$blog['id'])}}">
                            <i data-feather="eye" class="me-50"></i>
                            <span>{{_t('dashboard.Show')}}</span>
                        </a>
                        @endpermission

                        @permission('delete_blog')
                        <div class="col-4">
                            <form method="post" id="myForm"
                                  action="{{route('social.blog.york.destroy',$blog['id'])}}">
                                @csrf
                                @method('DELETE')
                                <button
                                    style="display: inline-flex;width: 137px;"
                                    class="btn delete dropdown-item"><i
                                        data-feather="trash" class="me-50"></i>
                                    <span>{{_t('dashboard.Delete')}}</span></button>
                            </form>
                        </div>
                        @endpermission
                    </div>
                </div>
            </td>
        </tr>
    @endforeach
    {{--<tr>--}}
    <td colspan="3">
        {!! $blogs->appends(request()->query())->links("pagination::bootstrap-4") !!}
    </td>
    {{--</tr>--}}
@else
    @include('admin.include.no_data')
@endif

<script>
    $(document).ready(function () {
        feather.replace()
    })
</script>